cart/urls.py
from django.contrib import admin
from django.urls import path

from cart import views
app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('cart/', views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
    ]

ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('searchapp.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

searchapp/urls.py
from django.urls import path


from . import views

app_name = 'searchapp'

urlpatterns = [
    path('', views. searchresult, name='searchresult')]

shop/urls.py
from django.urls import path

from shop import views
app_name='shop'
urlpatterns = [
    path('',views.allprodcat,name='allprodcat'),
    path('shop/<slug:c_slug>/',views.allprodcat,name='products_by_category'),
    path('shop/<slug:c_slug>/<slug:p_slug>/',views.product_details,name='products_category_detail')
]

cart/models.py
from django.db import models
from shop.models import product

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def subtotal(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}'.format(self.product)

searchapp/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category_pics',blank=True)

    class Meta:
       ordering=('name',)
       verbose_name='category'
       verbose_name_plural='categories'

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])
    def __str__(self):
       return '{}'.format(self.name)

class product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    category=models.ForeignKey(category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product_pics',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField()
    created=models.DateTimeField(auto_now_add=True)
    update=models.DateTimeField(auto_now_add=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)

    def get_url(self):
        return reverse('shop:products_category_detail',args=[self.category.slug ,self.slug])

    class Meta:
       ordering=('name',)
       verbose_name='product'
       verbose_name_plural='products'

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from cart.models  import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from shop.models import product


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key

    if not cart:
        request.session.create()
    return cart


def add_cart(request, product_id):
    products = product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=products, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
          cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=products,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0):
    cart_items = []
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', {'cart_items': cart_items, 'total': total, 'counter': counter})
def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product_instance = get_object_or_404(product, id=product_id)

    try:
        cart_item = CartItem.objects.get(product=product_instance, cart=cart)

        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()

    except CartItem.DoesNotExist:
        pass

    return redirect('cart:cart_detail')

def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product_instance = get_object_or_404(product, id=product_id)

    try:
        cart_item = CartItem.objects.get(product=product_instance, cart=cart)
        cart_item.delete()

    except CartItem.DoesNotExist:
        pass

    return redirect('cart:cart_detail')

searchapp/views.py
from django.shortcuts import render
from shop.models import product
from django.db.models import Q

# Create your views here.
def searchresult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=product.objects.all().filter(Q(name__contains=query)|Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import category,product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.
def allprodcat(request, c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(category,slug=c_slug)
        products_list=product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)

    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,"category.html",{'category':c_page,'products':products})

def product_details(request,c_slug,p_slug):
    try:
        Product_instance=get_object_or_404(product,category__slug=c_slug,slug=p_slug)
    except Exception as e:
        raise e
    return render(request,"product.html",{'Product_instance':Product_instance})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,300&display=swap" rel="stylesheet">
    <link  href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}">
    <script src="https://kit.fontawesome.com/1b99dd44bf.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">

    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Items you are adding to the cart will be displayed here
{% endblock %}
{% block title %}
    Add to Cart
{% endblock %}
{% block content %}
    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my-title">
                    Cart is empty
                </h1>
                <br>
                <p class="text-center">
                    Please click <a href="{% url 'shop:allprodcat' %}">Here</a> to continue shopping
                </p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center ">
                <br>
                <h1 class=" my-title text-center" style="font-size:20px;">
                    Your Shopping Cart
                </h1>
                <br>
            </div>
        </div>
        <div class="row mx-auto">
            <div class="text-center col-12 col-sm-12 col-md-12 col-lg-7">
                <table class="table my_custom_table" style="max-width: 50%;">
                    <thead class="my_custom_thead">
                        <tr>
                            <th><h5>items</h5></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="{{ cart_item.product.get_absolute_url }}">
                                        <img src="{{ cart_item.product.image.url }}" alt="image" class="float-left rounded custom_image" style="height:100px; width:100px;">
                                    </a>
                                </td>
                                <td class="text-left">
                                    {{ cart_item.product.name }}
                                    <br>
                                    SKU:{{ cart_item.Product.id }}
                                    <br>
                                    Price:&#8377;{{ cart_item.product.price }}
                                    <br>
                                    Qty:{{ cart_item.quantity }} X {{ cart_item }}
                                </td>
                                <td>
                                    &#8377; {{ cart_item.subtotal }}
                                </td>
                                <td>
                               {% if cart_item.quantity < cart_item.product.stock %}
                                <a href="{% url 'cart:add_cart' product_id=cart_item.product.id  %}" class="custom_a"><i class="custom_icon fa fa-plus"></i></a><br>
                                 &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id  %}" class="custom_icon"><i class="fa fa-minus"></i></a><br>
                                 &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash"></i></a><br>
                               {% else %}
                              <a href="{% url 'cart:cart_remove' cart_item.product.id  %}" class="custom_a"><i class="custom_icon fa fa-plus"></i></a>
                               &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id  %}" class="custom_icon"><i class="fa fa-minus"></i></a>
                              {% endif %}
                              </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-5 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th>Checkout</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                Please review shopping cart items before proceeding to payment
                            </td>
                        </tr>
                       <tr>
                           <td class="text-center">
                               <b>Your total is:</b><strong>{{total}}</strong>

                           </td>
                           <tr>
                           <td>

                              <a href="https://wa.me/9074492370" class="btn btn-primary" style="font-size: 12px; padding: 10px; background-color: Grey; color: white; padding: 10px;">Payment </a>

                           </td>
                           </tr>
                        </tr>
                    <tr>
                        <td>
                <div class="mx-auto">
                    <a href="{% url 'shop:allprodcat' %}" class="btn btn-secondary  my_custom_button ml-auto" style="font-size: 12px;padding:10px;">Continue shopping</a>
                </div>
                        </td>
                      </tr>
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription  %}
    {% if category %}
        {{category.description|truncatewords:155}}
    {% else %}
         Welcome to Global Supplements where you can buy
         high quality protein  in a lower rate
    {% endif %}
{% endblock %}

{% block title %}

    {% if category %}
        {{category.name}}-Global Supplements
    {% else %}
         see our new product updates-Global Supplements
    {% endif %}
{% endblock %}

{% block content %}
  {% if category %}
      <div class="container-fluid">
          <div class="row my_row_class">
              <div class="mx-auto">
              <p> <a href="{% url 'shop:allprodcat' %}"> Our Products</a> </p>
              </div>
          </div>
      </div>
  {% endif %}

<div class="mx-auto">
    {% if category %}
        <img  src="{{category.image.url}}" alt="{{category.name}}" style="width:100%; height:300px;">
</div>
<br>

<div>
    <h1>{{category.name}}</h1>
    <p> {{category.description}}</p>
</div>
    {% else  %}
     <div>
         <img class="my_image_banner my_image_padding " src="{% static 'img\banner.png' %}" alt="Our product" width="100%;" height="300px;">
     </div>
<br>
<div>
    <h1 class="text-center" style=" font-family: Times New Roman, Times, serif;"><b> OUR PRODUCT COLLECTIONS</b></h1>
    <p class="text-justify" style=" font-family: Times New Roman, Times, serif; font-size:20px;">The word Lorem Ipsum is derived from the Latin word which means “pain itself”. It is a kind of a text filler tool that is used by the webmaster on the website.
Basically, this tool is used to create dummy content on the website when it’s new.
It helps the designer plan where the content will sit. It helps in creating drafts of the content on the pages of the website. It originates from the Latin text but is seen as gibberish.
Sometimes, the reader gets distracted while creating or working on the website. That’s why this language is important.
This tool makes the work easier for the webmaster. When using Lorem Ipsum for creating dummy content for your newly created website, you can select the text formats you want from the tool. Like, words, sentences, or paragraphs</p>
</div>
    {% endif %}
<div class="container">
    <div class="row">
        {% for product in products.object_list %}
            <div class="my-bottom-margin col-12 col-sm-6 col-md-4 col-lg-4">
                <div class="card text-center" >
                    <a href="{{product.get_url}}">
                        <img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="width:120px; height:100px;">
                    </a>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>&#8377;{{product.price}}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>

        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}

        </div>
        {% endif %}

    </div>
    <br>
</div>

</div>
{% endblock %}

templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      display: flex;
      flex-direction: column;
      min-height: 100vh;
      margin: 0;
    }

    .content {
      flex: 1;
    }

    .footer {
      background-color: #f8f9fa;
      padding: 10px;
      text-align: center;
    }
  </style>
</head>
<body>

  <div class="content">
  </div>

  <footer class="footer">
    <p> & copy; Global supplements .All rights reserved</p>
   <div class="row">
    <div class="col">
    </div>
    <div class="col-auto">
        <a href="https://www.instagram.com/globalsupplements.in?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" class="text-decoration-none">
            <i class="fab fa-instagram"></i> Global_supplements
        </a>
    </div>
  </div>
  </footer>

</body>
</html>

templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shop:allprodcat' %}"></a>  <img alt="logoimage" src="{% static 'img\logo.png' %}" width="130px;">
    </center>
</header>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:allprodcat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shop:allprodcat' %}">ALL PRODUCTS</a></li>
                {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
                {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item" style="margin-top: 7px;" >
          <a class="nav_link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <div class="mx-auto" style="padding-right:100px;">
      <form class="form-inline my-2 my-lg-0" role="search" action="{% url 'searchapp:searchresult' %}" method="get">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success float-right" type="submit"><i class="fa-brands fa-searchengin"></i>Search</button>
      </form>
      </div>
    </div>
  </div>
 </nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ Product.description|truncatewords:155 }}
{% endblock %}

{% block title %}
    {% if category %}
        {{ Product.name }} - Global Supplements
    {% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row my-prod-row-class">
        <div class="col-md-8 mx-auto">
            <p>
                <a href="{% url 'shop:allprodcat' %}">Home</a> |<a href="{{Product.category.get_url}}">{{Product.category}}</a>|{{Product.name}} </p>
            </p>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-6">
            <div class="text-center">
                <img class="img-fluid product-banner-image" src="{{ Product_instance.image.url }}" alt="{{ Product_instance.name }}">
                <p>&#8377;{{ Product_instance.price }}</p>
            </div>
        </div>
        <div class="col-lg-6">
            <div>
                <h1 class="my-prod-title">{{ Product_instance.name }}</h1>
                <h2 class="my-prod-title">Product Description</h2>
                <p class="my-prod-text" style="font-size:20px;">{{ Product_instance.description }}</p>
                {% if Product_instance.stock <= 0 %}
                    <p class="my-prod-title"><b>OUT OF STOCK</b></p>
                {% else %}
                    {% if Product_instance.id %}
                        <div class="text-center">
                            <a class="btn btn-secondary" href="{% url 'cart:add_cart' Product_instance.id %}">Add to Cart</a>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription  %}
         We have variety of products You can explore the world of Global supplements with a single click
{% endblock %}
{% block title %}
     Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my-search-text">You Have Searched for:<b>"{{query}}"</b></p>
</div>
<div class="container-fluid">
    <div class="row">
        {% for product in products %}
            <div class="my-bottom-margin col-12 col-sm-6 col-md-4 col-lg-4">
                <div class="card text-center" style="width: 10rem;">
                    <a href="{{product.get_url}}">
                        <img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}">
                    </a>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>&#8377;{{product.price}}</p>
                    </div>
                </div>
            </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my-search-text">0 Result Found</p>
        </div>
        {% endfor %}
 {% endblock %}